// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package provider_lambda

import (
	"context"

	"github.com/hashicorp/terraform-plugin-framework/provider/schema"
)

func LambdaProviderSchema(ctx context.Context) schema.Schema {
	return schema.Schema{}
}

type LambdaModel struct {
}
